name: Examples Nightly Run Matrix

on:
  workflow_dispatch:
    inputs:
      folders:
        description: 'Comma-separated list of folders'
        required: false
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight

jobs:
  check-commits:
    runs-on: rakitha
    outputs:
      new_commits: ${{ steps.check_commits.outputs.new_commits }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get current commit hash
        id: get_current_commit
        run: echo "current_commit=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Get previous commit hash
        id: get_previous_commit
        run: |
          if [ -f /Users/rperera/repo/git_hash/git_hash.txt ]; then
            previous_commit=$(cat /Users/rperera/repo/git_hash/git_hash.txt)
          else
            previous_commit=""
          fi
          echo "previous_commit=$previous_commit" >> $GITHUB_OUTPUT

      - name: Compare commit hashes
        id: check_commits
        run: |
          if [ "${{ steps.get_previous_commit.outputs.previous_commit }}" = "${{ steps.get_current_commit.outputs.current_commit }}" ]; then
            echo "new_commits=0" >> $GITHUB_OUTPUT
          else
            echo "new_commits=1" >> $GITHUB_OUTPUT
          fi

      - name: Send notification if no new commits
        if: steps.check_commits.outputs.new_commits == '0'
        run: |
          echo "No new commits found. Sending notification to Teams."

      - name: Save current commit hash
        if: steps.check_commits.outputs.new_commits == '1'
        run: echo "${{ steps.get_current_commit.outputs.current_commit }}" > /Users/rperera/repo/GitHubActionTest/git_hash//git_hash.txt
        continue-on-error: true

  process-folders:
    runs-on: rakitha
    needs: check-commits
    if: needs.check-commits.outputs.new_commits == '1'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Determine folders to process
        id: determine_folders
        run: |
            DEFAULT_DIR= /Users/rperera/repo/test_folders
            if [ "${{ github.event.inputs.folders }}" ]; then
                echo "folders=${{ github.event.inputs.folders }}" >> $GITHUB_OUTPUT
            else
                folders=$(ls -d $DEFAULT_DIR/*/)
                echo "folders=${folders//$'\n'/,}" >> $GITHUB_OUTPUT
            fi

      - name: Iterate over folders and run action
        run: |
          IFS=',' read -r -a folder_array <<< "${{ steps.determine_folders.outputs.folders }}"
          for folder in "${folder_array[@]}"; do
            if [ -f "$folder/run_test.sh" ]; then
              echo "Running action for folder: $folder"
              gh workflow run nightly-run.yml -f folder_name=$(basename $folder)
            else
              echo "run_test.sh not found in $folder, skipping..."
            fi
