name: Examples Nightly Run Matrix

on:
  push:
  workflow_dispatch:
    inputs:
      folders:
        description: 'Comma-separated list of folders'
        required: false
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight

env:
    GIT_HASH_FILE: /Users/rperera/repo/git_hash/git_hash.txt

jobs:
  check-commits:
    runs-on: rakitha
    outputs:
      new_commits: ${{ steps.check_commits.outputs.new_commits }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get current commit hash
        id: get_current_commit
        run: echo "current_commit=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Get previous commit hash
        id: get_previous_commit
        run: |
          if [ -f $GIT_HASH_FILE ]; then
            previous_commit=$(cat $GIT_HASH_FILE)
          else
            previous_commit=""
          fi
          echo "previous_commit=$previous_commit" >> $GITHUB_OUTPUT

      - name: Compare commit hashes
        id: check_commits
        run: |
          if [ "${{ steps.get_previous_commit.outputs.previous_commit }}" = "${{ steps.get_current_commit.outputs.current_commit }}" ]; then
            echo "new_commits=0" >> $GITHUB_OUTPUT
          else
            echo "new_commits=1" >> $GITHUB_OUTPUT
          fi

      - name: Send notification if no new commits
        if: steps.check_commits.outputs.new_commits == '0'
        run: |
          echo "No new commits found. Sending notification to Teams."

      - name: Save current commit hash
        if: steps.check_commits.outputs.new_commits == '1'
        run: echo "${{ steps.get_current_commit.outputs.current_commit }}" > $GIT_HASH_FILE
        continue-on-error: true

  process-folders:
    runs-on: rakitha
    needs: check-commits
    outputs:
        folders: ${{ steps.determine_folders.outputs.folders }}
    if: needs.check-commits.outputs.new_commits == '1'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Determine folders to process
        id: determine_folders
        run: |
            if [ "${{ github.event.inputs.folders }}" ]; then
                echo "folders=${{ github.event.inputs.folders }}" >> $GITHUB_OUTPUT
            else
                DEFAULT_DIR="/Users/rperera/repo/test_folders"
                folders=$(ls -d $DEFAULT_DIR/*/)
                folders_comma_separated=${folders//$'\n'/,}
                folders_json=$(echo $folders_comma_separated | jq -R 'split(",")')
                echo "folders=$folders_json" >> $GITHUB_OUTPUT
            fi
            echo "folder output ${{ steps.determine_folders.outputs.folders }}"

  examples-matrix:
      runs-on: rakitha
      needs: process-folders    
      strategy:
        max-parallel: 2
        fail-fast: false
        matrix:
          example_name: ${{ fromJson(needs['process-folders'].outputs.folders) }}
      steps:
          - name: Run nightly-run workflow
            uses: ./.github/workflows/nightly-run.yml
            with:
              example_name: ${{ matrix.example_name }}
