name: Multi-Folder Workflow

on:
  workflow_dispatch:
    inputs:
      folders:
        description: 'Comma-separated list of folders'
        required: false
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight

jobs:
  check-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check for new commits
        id: check_commits
        run: |
          git fetch origin
          COMMITS=$(git rev-list HEAD...origin/main --count)
          echo "new_commits=$COMMITS" >> $GITHUB_ENV

      - name: Send notification if no new commits
        if: env.new_commits == '0'
        run: |
          echo "No new commits found. Sending notification to Teams."

  process-folders:
    runs-on: ubuntu-latest
    needs: check-commits
    if: env.new_commits != '0'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set default directory
        run: echo "DEFAULT_DIR=/illumina-sdcolo-02/scratch/Descartes/testing/mapflow/repo" >> $GITHUB_ENV

      - name: Determine folders to process
        id: determine_folders
        run: |
          if [ "${{ github.event.inputs.folders }}" ]; then
            echo "folders=${{ github.event.inputs.folders }}" >> $GITHUB_ENV
          else
            folders=$(ls -d $DEFAULT_DIR/*/)
            echo "folders=${folders//$'\n'/,}" >> $GITHUB_ENV

      - name: Iterate over folders and run action
        run: |
          IFS=',' read -r -a folder_array <<< "${{ env.folders }}"
          for folder in "${folder_array[@]}"; do
            if [ -f "$folder/run_test.sh" ]; then
              echo "Running action for folder: $folder"
              gh workflow run another-workflow.yml -f folder_name=$(basename $folder)
            else
              echo "run_test.sh not found in $folder, skipping..."
            fi
