name: Snyk Test

on:
  workflow_dispatch:
  push:

jobs:
  build_example:
    runs-on: rakitha
    steps:
      - name: clone repo
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: build
        run: |
          . "/Users/rperera/miniforge3/etc/profile.d/conda.sh"
          cd /Users/rperera/repo/spatial-aligner
          conda env create -y -f environment.yml
          conda activate spal
      - name: snyk test - frontend
        run: | 
          cd /Users/rperera/repo/spatial-aligner/frontend 
          snyk test --all-projects
          snyk code test --severity-threshold=medium
      - name: snyk test - backend 
        run: |
          cd /Users/rperera/repo/spatial-aligner/backend
          pip freeze > requirements.txt
          snyk test --all-projects --command=python3
          snyk code test --severity-threshold=medium
      - name: snyk test - backend 
        run: |
          cd /Users/rperera/repo/spatial-aligner/cpp_backend
          snyk test --unmanaged --print-deps
          snyk code test --severity-threshold=medium


          