name: Snyk Test

on:
  workflow_dispatch:
  push:

jobs:
  build_example:
    runs-on: rakitha
    env:
      SNYK_SEVERITY_THRESHOLD: high  # Define the severity threshold as an environment variable

    steps:
      - name: clone repo
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: snyk test - frontend
        run: | 
          cd /Users/rperera/repo/spatial-aligner/frontend 
          snyk test --all-projects --severity-threshold=$SNYK_SEVERITY_THRESHOLD
          snyk code test --severity-threshold=$SNYK_SEVERITY_THRESHOLD
      - name: snyk test - backend 
        run: |
          pwd
          cd backend
          pip freeze > requirements.txt
          snyk test --all-projects --command=python3 --severity-threshold=$SNYK_SEVERITY_THRESHOLD
          snyk code test --severity-threshold=$SNYK_SEVERITY_THRESHOLD
      - name: snyk test - C++ backend 
        run: |
          pwd
          cd cpp_backend
          snyk test --unmanaged --print-deps --severity-threshold=$SNYK_SEVERITY_THRESHOLD
          snyk code test --severity-threshold=$SNYK_SEVERITY_THRESHOLD



          